### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by florian-lefebvre** [op-ent/api#10]
A voir comment on peut mettre en place Swagger pour documenter l'API. Il faut aussi regarder comment intégrer les specs OpenApi.

**Comment by florian-lefebvre** [comment]
Je pense que le plus simple c'est de setup swagger avec docker (super facile avec docker compose) et de renseigner une spec json à la main. Si on s'y met rapidement, il suffit de compléter la doc à chaque fois qu'on rajoute des endpoints. Je pense pas que ça vaille le coup de créer un vrai package Swagger pour Adonis, comme https://github.com/nestjs/swagger

**Comment by MRakox** [comment]
Je propose plutôt d'utiliser ce module : 
https://github.com/ad-on-is/adonis-autoswagger

**Comment by florian-lefebvre** [comment]
Bonne idée !
