### ISSUE TITLE
Notification service

### ISSUE THREAD

**Issue by florian-lefebvre** [op-ent/api#16]
Communication is essential, and we need this feature for #5. We'll use https://novu.co/.

**Comment by Micorksen** [comment]
Oh, great !
For SMS we can use Infomaniak (https://sms.infomaniak.com)

![Image](https://user-images.githubusercontent.com/35396314/193425764-64643c73-9a2d-4491-823d-9c39cda574b8.png)

<img src="https://user-images.githubusercontent.com/35396314/193425885-01fa0cb3-c662-4008-95f1-ed75e9c38155.png" width="250" />
<img src="https://user-images.githubusercontent.com/35396314/193425922-d75d0291-308a-4456-8d76-4845c6f80d6f.png" width="250" />

**Comment by florian-lefebvre** [comment]
Voyons ça dans #22
